#!/usr/bin/env bash
set -Eeuo pipefail

    XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
    XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
    XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
    THEME_DIR="${LIVARA_THEME_ROOT:-$XDG_STATE_HOME/livara/theme}"
    SHELL_NAME="${LIVARA_SHELL_NAME:-Livara}"
    LOG_DIR="$XDG_STATE_HOME/livara/logs"
    LOG_FILE="$LOG_DIR/theme-sync.log"
    FOLIATE_CONFIG_HOME="$XDG_CONFIG_HOME/com.github.johnfactotum.Foliate"
    FOLIATE_FLATPAK_HOME="$HOME/.var/app/com.github.johnfactotum.Foliate/config/com.github.johnfactotum.Foliate"
    VESKTOP_CONFIG_HOME="$XDG_CONFIG_HOME/vesktop"
    VESKTOP_FLATPAK_HOME="$HOME/.var/app/dev.vencord.Vesktop/config/vesktop"
    XOURNAL_PALETTE_NAME="livara.gpl"
    FASTFETCH_CAT_SOURCE="${LIVARA_FASTFETCH_CAT_PNG:-$HOME/.local/share/livara/assets/fastfetch-cat.png}"
    FASTFETCH_CAT_OUTPUT="$THEME_DIR/fastfetch-cat.png"
    FASTFETCH_CAT_STATE="$THEME_DIR/fastfetch-cat.state"
    HYDRA_THEME_NAME="${LIVARA_HYDRA_THEME_NAME:-Livara}"
    HYDRA_FRIEND_CODE="${LIVARA_HYDRA_FRIEND_CODE:-}"
    case "$HYDRA_THEME_NAME" in
      ""|*/*|*\\*) HYDRA_THEME_NAME="Livara" ;;
    esac
    [[ "$HYDRA_FRIEND_CODE" =~ ^[[:alnum:]]+$ ]] || HYDRA_FRIEND_CODE=""
    HYDRA_THEME_ID="$HYDRA_THEME_NAME-${HYDRA_FRIEND_CODE:-local}"
    HYDRA_USER_DATA_ROOT="${LIVARA_HYDRA_USER_DATA:-$XDG_CONFIG_HOME/Hydra}"
    HYDRA_THEME_DIR="$HYDRA_USER_DATA_ROOT/themes/$HYDRA_THEME_ID"
    HYDRA_THEME_EXPORT_DIR="$THEME_DIR/hydra-export/themes/$HYDRA_THEME_ID"
    HYDRA_SCREENSHOT_SOURCE="${LIVARA_HYDRA_SCREENSHOT:-}"
    HYDRA_SCREENSHOT="$HYDRA_THEME_DIR/screenshot.png"
    if [[ "${1:-dark}" != dark ]]; then
      printf 'Livara supports only the dark palette variant\n' >&2
      exit 2
    fi
    PALETTE_VARIANT=dark
    PALETTE_FILE="$THEME_DIR/palette.$PALETTE_VARIANT.json"
    BTOP_CONFIG="$XDG_CONFIG_HOME/btop/btop.conf"
    BTOP_THEME="$XDG_CONFIG_HOME/btop/themes/Livara.theme"
    WEZTERM_SCHEME="${LIVARA_WEZTERM_COLOR_SCHEME:-$SHELL_NAME}"
    WEZTERM_THEME="$XDG_CONFIG_HOME/wezterm/colors/$WEZTERM_SCHEME.toml"
    # NixVim/Home Manager exposes the generated Lua module under lua/.
    NVIM_THEME_PATH="$XDG_CONFIG_HOME/nvim/lua/matugen_colors.lua"
    FREESM_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/FreesmLauncher"
    FREESM_FLATPAK_HOME="$HOME/.var/app/org.freesmlauncher.FreesmLauncher/data/FreesmLauncher"
    LOCK_FILE="${LIVARA_LOCK_FILE:-$XDG_STATE_HOME/livara/theme-sync.lock}"
    if [[ "${LIVARA_LOCK_HELD:-0}" != 1 ]]; then
      mkdir -p "$(dirname "$LOCK_FILE")"
      exec 9>"$LOCK_FILE"
      if ! flock -n 9; then
        printf 'theme synchronization already running; skipping application adapters\n' >&2
        exit 0
      fi
    fi
    mkdir -p "$THEME_DIR" "$LOG_DIR"
    log() { printf '[%s] %s\n' "$(date --iso-8601=seconds)" "$*" | tee -a "$LOG_FILE"; }

    # The application adapters below consume each ecosystem's documented
    # format. The selected shell owns palette production; this adapter only
    # consumes the requested neutral variant and publishes projections.
    if [[ ! -s "$THEME_DIR/palette.json" ]]; then
      install -m 0644 "${LIVARA_DEFAULT_PALETTE:-$THEME_DIR/bootstrap.json}" "$THEME_DIR/palette.json"
      log "installed the emergency Livara fallback palette"
    fi
    if [[ ! -s "$PALETTE_FILE" ]]; then
      if [[ -s "$THEME_DIR/palette.json" ]]; then
        cp -f "$THEME_DIR/palette.json" "$PALETTE_FILE"
        log "palette.$PALETTE_VARIANT.json missing; using the active palette as an explicit fallback"
      else
        log "palette.$PALETTE_VARIANT.json and palette.json are missing"
        exit 1
      fi
    fi
    jq -e 'type == "object" and all(.[]; type == "string" and test("^#[0-9A-Fa-f]{6}$"))' "$PALETTE_FILE" >/dev/null || {
      log "palette.$PALETTE_VARIANT.json is invalid"
      exit 1
    }
    json_color() {
      local key="$1"
      local fallback="${2:-base}"
      local color
      if ! color="$(jq -er --arg key "$key" --arg fallback "$fallback" '.[$key] // .[$fallback] // .base // error("missing color")' "$PALETTE_FILE")"; then
        log "palette is missing required color role: $key"
        return 1
      fi
      if [[ "$color" =~ ^#[[:xdigit:]]{6}$ ]]; then
        printf '%s\n' "$color"
      else
        log "palette contains invalid color role: $key"
        return 1
      fi
      }

    sync_browser_theme() {
      local browser_css="$THEME_DIR/browser/firefox.css"
      write_atomic "$browser_css" <<EOF
/* Generated by Livara for Firefox/Zen userChrome.css. */
:root {
  --livara-base: $(json_color browser_chrome_bg base);
  --livara-surface: $(json_color browser_surface surface0);
  --livara-surface-raised: $(json_color browser_surface_raised surface1);
  --livara-surface-active: $(json_color browser_surface_active surface2);
  --livara-text: $(json_color browser_text text);
  --livara-muted: $(json_color browser_muted subtext0);
  --livara-primary: $(json_color browser_accent primary);
  --livara-primary-container: $(json_color browser_accent_container primary_container);
  --livara-on-primary: $(json_color browser_on_accent on_primary);
  --livara-border: $(json_color browser_border overlay0);
}

@-moz-document url-prefix("chrome://browser/content/browser.xhtml") {
  /* Firefox and Zen keep the browser chrome separate from web content. */
  :root,
  #main-window,
  #browser,
  #zen-main-app-wrapper,
  #zen-browser-background,
  #zen-appcontent-wrapper,
  #zen-tabbox-wrapper,
  #tabbrowser-tabbox,
  #tabbrowser-tabpanels {
    background: var(--livara-base) !important;
    color: var(--livara-text) !important;
  }

  #zen-browser-background::before,
  #zen-browser-background::after {
    background: var(--livara-base) !important;
    opacity: 1 !important;
  }

  #navigator-toolbox,
  #TabsToolbar,
  #nav-bar,
  #PersonalToolbar,
  #zen-appcontent-navbar-wrapper,
  #zen-appcontent-navbar-container {
    background: var(--livara-base) !important;
    color: var(--livara-text) !important;
    border-color: var(--livara-border) !important;
  }

  #zen-tabs-wrapper,
  #zen-sidebar-top-buttons,
  #zen-sidebar-foot-buttons,
  #sidebar-box,
  #sidebar-header,
  #zen-sidebar-splitter,
  #appcontent,
  #statuspanel,
  #findbar {
    background: var(--livara-base) !important;
    color: var(--livara-text) !important;
    border-color: var(--livara-border) !important;
  }

  #zen-essentials {
    background: var(--livara-surface) !important;
    color: var(--livara-text) !important;
    border: 1px solid var(--livara-border) !important;
    border-bottom-color: var(--livara-primary) !important;
  }

  #zen-sidebar-top-buttons,
  #zen-sidebar-foot-buttons,
  #zen-expand-sidebar-button,
  #zen-workspaces-button,
  #zen-create-new-button {
    background: transparent !important;
    border-color: transparent !important;
  }

  #zen-tabs-wrapper,
  #zen-essentials,
  #sidebar-box,
  #sidebar-header,
  #zen-sidebar-foot-buttons,
  #zen-sidebar-top-buttons {
    box-shadow: none !important;
  }

  #urlbar,
  #urlbar-background,
  .urlbar-background,
  #searchbar,
  .urlbar-input-container,
  .searchbar-textbox {
    background: var(--livara-surface) !important;
    color: var(--livara-text) !important;
    border-color: var(--livara-border) !important;
  }

  #urlbar-input,
  .urlbar-input,
  .searchbar-textbox {
    color: var(--livara-text) !important;
    fill: var(--livara-text) !important;
  }

  toolbarbutton,
  #zen-sidebar-foot-buttons toolbarbutton,
  #zen-sidebar-top-buttons toolbarbutton {
    background: transparent !important;
    color: var(--livara-text) !important;
    fill: var(--livara-text) !important;
    -moz-context-properties: fill, fill-opacity, stroke, stroke-opacity !important;
  }

  toolbarbutton > .toolbarbutton-icon,
  toolbarbutton > .toolbarbutton-badge-stack,
  #zen-sidebar-foot-buttons toolbarbutton > *,
  #zen-sidebar-top-buttons toolbarbutton > * {
    background: var(--livara-surface) !important;
    color: var(--livara-text) !important;
    fill: var(--livara-text) !important;
    border: 1px solid transparent !important;
  }

  toolbarbutton:hover,
  menu:hover,
  menuitem:hover,
  .subviewbutton:hover,
  .toolbarbutton-1:hover,
  #zen-sidebar-foot-buttons toolbarbutton:hover,
  #zen-sidebar-top-buttons toolbarbutton:hover {
    background: transparent !important;
    color: var(--livara-text) !important;
    fill: var(--livara-text) !important;
  }

  toolbarbutton:hover > .toolbarbutton-icon,
  toolbarbutton:hover > .toolbarbutton-badge-stack,
  #zen-sidebar-foot-buttons toolbarbutton:hover > *,
  #zen-sidebar-top-buttons toolbarbutton:hover > * {
    background: var(--livara-surface-raised) !important;
    border-color: var(--livara-border) !important;
  }

  toolbarbutton[checked="true"],
  toolbarbutton[open="true"],
  toolbarbutton[aria-pressed="true"],
  .subviewbutton[checked="true"],
  .tabbrowser-tab[selected="true"] .tab-background {
    background: var(--livara-primary-container) !important;
    color: var(--livara-on-primary) !important;
    fill: var(--livara-on-primary) !important;
  }

  #zen-sidebar-foot-buttons toolbarbutton[open="true"],
  #zen-sidebar-foot-buttons toolbarbutton[checked="true"],
  #zen-sidebar-top-buttons toolbarbutton[open="true"],
  #zen-sidebar-top-buttons toolbarbutton[checked="true"] {
    background: var(--livara-primary-container) !important;
    color: var(--livara-on-primary) !important;
    fill: var(--livara-on-primary) !important;
  }

  .tabbrowser-tab .tab-background {
    background: var(--livara-surface) !important;
    border-color: var(--livara-border) !important;
  }

  .tabbrowser-tab[selected="true"] .tab-label,
  .tabbrowser-tab[selected="true"] .tab-icon-image,
  .tabbrowser-tab[selected="true"] .tab-throbber {
    color: var(--livara-on-primary) !important;
    fill: var(--livara-on-primary) !important;
  }

  .tabbrowser-tab:not([selected="true"]) .tab-label,
  #sidebar-header,
  #sidebar-box {
    color: var(--livara-muted) !important;
  }

  #sidebar-splitter,
  #zen-sidebar-splitter,
  .sidebar-splitter {
    border-color: var(--livara-border) !important;
  }

  /* Zen compact mode controls geometry upstream; these rules only paint it. */
  :root[zen-compact-mode="true"] #zen-appcontent-navbar-wrapper,
  :root[zen-compact-mode-active="true"] #navigator-toolbox,
  :root[zen-has-hover="true"] #navigator-toolbox,
  :root[zen-user-show="true"] #navigator-toolbox,
  :root[has-popup-menu="true"] #navigator-toolbox {
    background: var(--livara-base) !important;
    color: var(--livara-text) !important;
  }

  /* Firefox panels, menus, downloads and the Zen three-dot panel. */
  panel,
  panelview,
  menupopup,
  menu,
  menuitem,
  .panel-subview-body,
  .subviewbutton,
  #PanelUI-popup,
  #appMenu-popup,
  #downloadsPanel,
  #downloadsListBox {
    background: var(--livara-base) !important;
    color: var(--livara-text) !important;
    border-color: var(--livara-border) !important;
  }
}
EOF
    }

    sync_nvim_palette() {
      local tmp
      tmp="$(mktemp)"
      jq -r 'to_entries | map("  " + .key + " = " + (.value | @json) + ",") | "return {\n" + join("\n") + "\n}\n"' \
        "$PALETTE_FILE" > "$tmp"
      write_atomic "$NVIM_THEME_PATH" < "$tmp"
      rm -f "$tmp"
    }

    hex_to_rgb() {
      local hex="${1#\#}"
      [[ "${#hex}" == 6 ]] || hex=000000
      printf '%d %d %d' "0x${hex:0:2}" "0x${hex:2:2}" "0x${hex:4:2}"
    }

    hex_to_argb_decimal() {
      local hex="${1#\#}"
      [[ "${#hex}" == 6 ]] || hex=000000
      printf '%u' "$((16#FF${hex}))"
    }

    write_atomic() {
      local target="$1"
      local target_dir tmp
      target_dir="$(dirname "$target")"
      mkdir -p "$target_dir"
      tmp="$(mktemp "$target_dir/.livara-theme.XXXXXX")"
      cat > "$tmp"
      chmod 0644 "$tmp"
      mv -f -- "$tmp" "$target"
      }

    sync_gtk_theme() {
      write_atomic "$XDG_CONFIG_HOME/gtk-3.0/gtk.css" <<EOF
/* Generated by Livara from palette.$PALETTE_VARIANT.json. */
.sidebar, .sidebar:backdrop, GtkPlacesSidebar,
.navigation-sidebar, .navigation-sidebar:backdrop {
  background-color: $(json_color gtk_window_bg);
  color: $(json_color text);
}
.view, .view:backdrop, treeview, textview {
  background-color: $(json_color gtk_view_bg);
  color: $(json_color text);
}
*:selected {
  background-color: $(json_color primary);
  color: $(json_color on_primary);
}
EOF
      write_atomic "$XDG_CONFIG_HOME/gtk-4.0/gtk.css" <<EOF
/* Generated by Livara using libadwaita's documented custom properties. */
:root {
  --window-bg-color: $(json_color gtk_window_bg);
  --window-fg-color: $(json_color text);
  --view-bg-color: $(json_color gtk_view_bg);
  --view-fg-color: $(json_color text);
  --headerbar-bg-color: $(json_color gtk_view_bg);
  --headerbar-fg-color: $(json_color text);
  --headerbar-border-color: $(json_color overlay0);
  --sidebar-bg-color: $(json_color gtk_view_bg);
  --sidebar-fg-color: $(json_color text);
  --sidebar-border-color: $(json_color overlay0);
  --card-bg-color: $(json_color gtk_card_bg);
  --card-fg-color: $(json_color text);
  --popover-bg-color: $(json_color gtk_popover_bg);
  --popover-fg-color: $(json_color text);
  --dialog-bg-color: $(json_color gtk_popover_bg);
  --dialog-fg-color: $(json_color text);
  --accent-bg-color: $(json_color primary);
  --accent-fg-color: $(json_color on_primary);
  --accent-color: $(json_color primary);
  --destructive-bg-color: $(json_color error);
  --destructive-fg-color: $(json_color on_error);
  --destructive-color: $(json_color error);
  --success-bg-color: $(json_color green);
  --success-fg-color: $(json_color base);
  --success-color: $(json_color green);
  --warning-bg-color: $(json_color yellow);
  --warning-fg-color: $(json_color base);
  --warning-color: $(json_color yellow);
  --error-bg-color: $(json_color error);
  --error-fg-color: $(json_color on_error);
  --error-color: $(json_color error);
}
.navigation-sidebar, .navigation-sidebar:backdrop {
  background-color: var(--sidebar-bg-color);
  color: var(--sidebar-fg-color);
}
EOF
      write_atomic "$XDG_CONFIG_HOME/gtk-3.0/settings.ini" <<EOF
[Settings]
gtk-theme-name=Adwaita
gtk-icon-theme-name=Livara-Kora
gtk-application-prefer-dark-theme=true
EOF
      write_atomic "$XDG_CONFIG_HOME/gtk-4.0/settings.ini" <<EOF
[Settings]
gtk-theme-name=Adwaita
gtk-icon-theme-name=Livara-Kora
gtk-interface-color-scheme=dark
EOF
      log "GTK3/GTK4 native CSS and preference files synchronized for $PALETTE_VARIANT mode"
    }

    sync_gtk_theme
    sync_browser_theme
    sync_nvim_palette

    sync_fastfetch_cat() {
      [[ -s "$FASTFETCH_CAT_SOURCE" ]] || {
        log "Fastfetch cat source not available: $FASTFETCH_CAT_SOURCE"
        return 0
      }
      command -v convert >/dev/null 2>&1 || {
        log "Fastfetch cat skipped: ImageMagick convert is unavailable"
        return 0
      }

      local color source_hash signature current_signature
      local png_tmp="$FASTFETCH_CAT_OUTPUT.tmp.$$"
      local state_tmp="$FASTFETCH_CAT_STATE.tmp.$$"
      color="$(json_color primary blue)"
      [[ "$color" =~ ^#[[:xdigit:]]{6}$ ]] || color="#7bb7ff"
      source_hash="$(sha256sum "$FASTFETCH_CAT_SOURCE" | cut -d' ' -f1)"
      signature="$color $source_hash"
      current_signature=""
      [[ -s "$FASTFETCH_CAT_STATE" ]] && current_signature="$(<"$FASTFETCH_CAT_STATE")"
      if [[ -s "$FASTFETCH_CAT_OUTPUT" && "$current_signature" == "$signature" ]]; then
        return 0
      fi
      if ! convert "$FASTFETCH_CAT_SOURCE" -alpha on -channel RGB -fill "$color" -colorize 100% +channel -strip "PNG32:$png_tmp" >/dev/null 2>&1; then
        rm -f "$png_tmp" "$state_tmp"
        log "Fastfetch cat colorization failed"
        return 0
      fi
      chmod 0644 "$png_tmp"
      printf '%s\n' "$signature" > "$state_tmp"
      chmod 0644 "$state_tmp"
      mv -f "$png_tmp" "$FASTFETCH_CAT_OUTPUT"
      mv -f "$state_tmp" "$FASTFETCH_CAT_STATE"
      log "Fastfetch cat synchronized: $FASTFETCH_CAT_OUTPUT"
    }

    sync_fastfetch_config() {
      local tmp primary text logo
      primary="$(json_color primary)"
      text="$(json_color text)"
      logo="$FASTFETCH_CAT_OUTPUT"
      tmp="$(mktemp)"
      jq -n --arg primary "$primary" --arg text "$text" --arg logo "$logo" '
        {
          "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
          logo: {source: $logo, type: "kitty-direct", width: 16, height: 9,
            padding: {top: 4, right: 3, left: 3}},
          display: {separator: " ", color: {keys: $primary, title: $primary, output: $text}},
          modules: [
            {type: "custom", key: "╭───────────╮", keyColor: $primary},
            {type: "title", key: "│  user    │", format: "{user-name}", keyColor: $primary},
            {type: "title", key: "│ 󰇅 hname   │", format: "{host-name}", keyColor: $primary},
            {type: "uptime", key: "│ 󰅐 uptime  │", keyColor: $primary},
            {type: "os", key: "│ {icon} distro  │", keyColor: $primary},
            {type: "kernel", key: "│  kernel  │", keyColor: $primary},
            {type: "wm", key: "│  wm      │", keyColor: $primary},
            {type: "de", key: "│ 󰇄 desktop │", keyColor: $primary},
            {type: "terminal", key: "│  term    │", keyColor: $primary},
            {type: "shell", key: "│  shell   │", keyColor: $primary},
            {type: "cpu", key: "│ 󰍛 cpu     │", format: "{name}", keyColor: $primary},
            {type: "gpu", key: "│ 󰯦 gpu     │", format: "{name} ", detectionMethod: "auto", keyColor: $primary},
            {type: "disk", key: "│ 󰉉 disk    │", folders: ["/"], format: "{size-used} / {size-total}", keyColor: $primary},
            {type: "memory", key: "│  memory  │", keyColor: $primary},
            {type: "custom", key: "├───────────┤", keyColor: $primary},
            {type: "colors", key: "│  colors  │", symbol: "circle", keyColor: $primary},
            {type: "custom", key: "╰───────────╯", keyColor: $primary}
          ]
        }
      ' > "$tmp"
      write_atomic "$THEME_DIR/fastfetch.jsonc" < "$tmp"
      rm -f "$tmp"
    }

    sync_fastfetch_cat
    sync_fastfetch_config

    sync_wezterm_scheme() {
      write_atomic "$WEZTERM_THEME" <<EOF
[colors]
foreground = "$(json_color text)"
background = "$(json_color base)"
cursor_bg = "$(json_color primary)"
cursor_fg = "$(json_color base)"
cursor_border = "$(json_color primary)"
selection_fg = "$(json_color text)"
selection_bg = "$(json_color surface1)"
ansi = ["$(json_color base)", "$(json_color red)", "$(json_color green)", "$(json_color yellow)", "$(json_color blue)", "$(json_color mauve)", "$(json_color teal)", "$(json_color text)"]
brights = ["$(json_color surface1)", "$(json_color red)", "$(json_color green)", "$(json_color yellow)", "$(json_color blue)", "$(json_color mauve)", "$(json_color teal)", "$(json_color text)"]
EOF
      log "WezTerm scheme synchronized: $WEZTERM_THEME"
    }

    sync_btop_theme() {
      write_atomic "$BTOP_THEME" <<EOF
# Livara btop theme generated from the active palette.
theme[main_bg]="$(json_color base)"
theme[main_fg]="$(json_color text)"
theme[title]="$(json_color text)"
theme[hi_fg]="$(json_color primary)"
theme[selected_bg]="$(json_color primary)"
theme[selected_fg]="$(json_color on_primary)"
theme[inactive_fg]="$(json_color subtext0)"
theme[graph_text]="$(json_color secondary)"
theme[meter_bg]="$(json_color surface1)"
theme[proc_misc]="$(json_color tertiary)"
theme[cpu_box]="$(json_color primary)"
theme[mem_box]="$(json_color secondary)"
theme[net_box]="$(json_color tertiary)"
theme[proc_box]="$(json_color blue)"
theme[div_line]="$(json_color overlay0)"
theme[temp_start]="$(json_color green)"
theme[temp_mid]="$(json_color yellow)"
theme[temp_end]="$(json_color red)"
theme[cpu_start]="$(json_color green)"
theme[cpu_mid]="$(json_color primary)"
theme[cpu_end]="$(json_color red)"
theme[free_end]="$(json_color green)"
theme[free_mid]="$(json_color secondary)"
theme[free_start]="$(json_color red)"
theme[cached_start]="$(json_color green)"
theme[cached_mid]="$(json_color secondary)"
theme[cached_end]="$(json_color red)"
theme[available_start]="$(json_color red)"
theme[available_mid]="$(json_color yellow)"
theme[available_end]="$(json_color green)"
theme[used_start]="$(json_color green)"
theme[used_mid]="$(json_color yellow)"
theme[used_end]="$(json_color red)"
theme[download_start]="$(json_color green)"
theme[download_mid]="$(json_color secondary)"
theme[download_end]="$(json_color red)"
theme[upload_start]="$(json_color green)"
theme[upload_mid]="$(json_color secondary)"
theme[upload_end]="$(json_color red)"
theme[process_start]="$(json_color subtext1)"
theme[process_mid]="$(json_color primary)"
theme[process_end]="$(json_color tertiary)"
theme[proc_pause_bg]="$(json_color red)"
theme[proc_follow_bg]="$(json_color blue)"
theme[proc_banner_bg]="$(json_color surface1)"
theme[proc_banner_fg]="$(json_color on_secondary)"
theme[followed_bg]="$(json_color blue)"
theme[followed_fg]="$(json_color text)"
EOF
      mkdir -p "$(dirname "$BTOP_CONFIG")"
      if [[ -s "$BTOP_CONFIG" ]]; then
        local config_tmp
        config_tmp="$(mktemp)"
        awk '
          BEGIN { replaced = 0 }
          /^color_theme[[:space:]]*=/ { print "color_theme = \"Livara\""; replaced = 1; next }
          { print }
          END { if (!replaced) print "color_theme = \"Livara\"" }
        ' "$BTOP_CONFIG" > "$config_tmp"
        write_atomic "$BTOP_CONFIG" < "$config_tmp"
        rm -f "$config_tmp"
      else
        printf 'color_theme = "Livara"\n' | write_atomic "$BTOP_CONFIG"
      fi
      if pgrep -x btop >/dev/null 2>&1; then
        pkill -USR2 -x btop || true
        log "btop theme reloaded through SIGUSR2"
      fi
    }

    sync_wezterm_scheme
    sync_btop_theme

    sync_hydra_theme_root() {
      local root="$1"
      mkdir -p "$root"
      local screenshot_name="screenshot.png"
      rm -f "$root"/screenshot.*
      if [[ -n "$HYDRA_SCREENSHOT_SOURCE" ]]; then
        if [[ ! -s "$HYDRA_SCREENSHOT_SOURCE" ]]; then
          log "Hydra screenshot skipped because the configured file is missing: $HYDRA_SCREENSHOT_SOURCE"
        else
          local screenshot_extension="${HYDRA_SCREENSHOT_SOURCE##*.}"
          screenshot_extension="${screenshot_extension,,}"
          case "$screenshot_extension" in
            png|webp|jpg|jpeg|avif|heic|heif)
              screenshot_name="screenshot.$screenshot_extension"
              cp -f "$HYDRA_SCREENSHOT_SOURCE" "$root/$screenshot_name"
              if [[ "$root" == "$HYDRA_THEME_DIR" ]]; then
                HYDRA_SCREENSHOT="$root/$screenshot_name"
              fi
              ;;
            *) log "Hydra screenshot skipped because its extension is unsupported: $HYDRA_SCREENSHOT_SOURCE" ;;
          esac
        fi
      fi
      write_atomic "$root/theme.css" <<EOF
:root {
  --livara-background: $(json_color base);
  --livara-surface: $(json_color surface0);
  --livara-surface-raised: $(json_color surface1);
  --livara-text: $(json_color text);
  --livara-muted: $(json_color subtext0);
  --livara-primary: $(json_color blue);
  --livara-secondary: $(json_color teal);
  --livara-error: $(json_color red);
}

html, body, #root { background: var(--livara-background) !important; color: var(--livara-text) !important; }
button, input, select, textarea, [role="button"] { background: var(--livara-surface) !important; color: var(--livara-text) !important; border-color: $(json_color overlay0) !important; }
button:hover, [role="button"]:hover { background: var(--livara-surface-raised) !important; border-color: var(--livara-primary) !important; }
a, [data-state="active"], .active { color: var(--livara-primary) !important; }
.error, [data-variant="error"] { color: var(--livara-error) !important; }
EOF
      write_atomic "$root/README.txt" <<EOF
Livara Hydra theme generated from the active shell palette.

Theme directory: $HYDRA_THEME_ID
CSS file: theme.css
Screenshot file: $screenshot_name
Friend code configured: $([[ -n "$HYDRA_FRIEND_CODE" ]] && printf true || printf false)
Submission readiness: $([[ -n "$HYDRA_FRIEND_CODE" && -s "$HYDRA_SCREENSHOT" ]] && printf true || printf false)

Hydra stores local themes in its LevelDB database and does not discover this
directory automatically in Settings > Appearance. Use Create theme in Hydra,
open the editor for the new theme, and replace its CSS with this theme.css.
EOF
    }

    sync_hydra_theme() {
      [[ -d "$HYDRA_USER_DATA_ROOT" ]] && sync_hydra_theme_root "$HYDRA_THEME_DIR"
      sync_hydra_theme_root "$HYDRA_THEME_EXPORT_DIR"
      if [[ -n "$HYDRA_FRIEND_CODE" && -s "$HYDRA_SCREENSHOT_SOURCE" ]]; then
        log "Hydra theme export ready for review: $HYDRA_THEME_EXPORT_DIR"
      else
        log "Hydra theme source generated; friend code and screenshot are still required: $HYDRA_THEME_EXPORT_DIR"
      fi
    }

    sync_hydra_theme

    sync_foliate_theme_root() {
      local root="$1"
      [[ -n "$root" && -d "$root" ]] || return 0
      local theme="$root/themes/Livara.json"
      mkdir -p "$(dirname "$theme")"
      write_atomic "$theme" <<EOF
{
  "label": "Livara",
  "light": {
    "fg": "$(json_color text)",
    "bg": "$(json_color base)",
    "link": "$(json_color blue)"
  },
  "dark": {
    "fg": "$(json_color text)",
    "bg": "$(json_color base)",
    "link": "$(json_color blue)"
  }
}
EOF
    }

    [[ -d "$FOLIATE_CONFIG_HOME" ]] && sync_foliate_theme_root "$FOLIATE_CONFIG_HOME"
    [[ -d "$FOLIATE_FLATPAK_HOME" ]] && sync_foliate_theme_root "$FOLIATE_FLATPAK_HOME"

    # Foliate is a GTK4/libadwaita application, but its reader appearance is
    # an application-level JSON theme consumed by the WebKit reader. The
    # selection key belongs to Foliate's GSettings schema
    # com.github.johnfactotum.Foliate (relocatable child path viewer/view,
    # key 'theme'). Native and Flatpak installations have separate settings
    # backends, so never query the host schema on behalf of the Flatpak sandbox.
    #
    # On NixOS the Foliate GSettings schema is typically NOT installed in the
    # host XDG_DATA_DIRS (it lives inside the Foliate package or Flatpak
    # runtime), so `gsettings` will fail with "No such schema". Use `dconf`
    # instead, which writes directly to the dconf database without requiring
    # any schema to be installed. For the Flatpak sandbox, GSettings uses a
    # keyfile backend at ~/.var/app/.../config/glib-2.0/settings/keyfile;
    # write to it directly since the sandbox is not running during activation.
    foliate_dconf_path="/com/github/johnfactotum/Foliate/viewer/view/theme"
    foliate_keyfile_section="com/github/johnfactotum/Foliate/viewer/view"
    sync_foliate_theme_selection() {
      local selected=false

      # Native: write directly to the dconf database. dconf does not need
      # the GSettings schema to be installed on the host.
      if command -v dconf >/dev/null 2>&1; then
        if dconf write "$foliate_dconf_path" "'Livara.json'" >/dev/null 2>&1; then
          log "Foliate native reader theme selected: Livara.json"
          selected=true
        else
          log "Foliate native reader theme generated; dconf write failed"
        fi
      fi

      # Flatpak: GSettings uses a keyfile backend inside the sandbox. The
      # keyfile is at ~/.var/app/.../config/glib-2.0/settings/keyfile and
      # uses dconf-style paths as section headers. Write to it directly so
      # the setting persists even when the Flatpak is not running.
      if [[ "$selected" != true ]] &&
         [[ -d "$HOME/.var/app/com.github.johnfactotum.Foliate" ]]; then
        local keyfile="$HOME/.var/app/com.github.johnfactotum.Foliate/config/glib-2.0/settings/keyfile"
        mkdir -p "$(dirname "$keyfile")"
        touch "$keyfile"
        # Rewrite the keyfile: replace any existing theme= line in the
        # target section, or add the section + key if absent. GVariant
        # strings are single-quoted.
        awk -v section="$foliate_keyfile_section" '
          BEGIN { in_section = 0; found = 0 }
          /^\[/ {
            if (in_section && !found) { print "theme='\''Livara.json\''"; found = 1 }
            in_section = ($0 == "[" section "]")
          }
          in_section && /^theme=/ { print "theme='\''Livara.json\''"; found = 1; next }
          { print }
          END { if (in_section && !found) { print "theme='\''Livara.json\''"; found = 1 } }
        ' "$keyfile" > "$keyfile.tmp.$$"
        # Ensure the section exists even if it was not present originally.
        if ! grep -q "^\[$foliate_keyfile_section\]$" "$keyfile.tmp.$$"; then
          printf '\n[%s]\ntheme='\''Livara.json\''\n' "$foliate_keyfile_section" >> "$keyfile.tmp.$$"
        fi
        mv -f "$keyfile.tmp.$$" "$keyfile"
        chmod 0644 "$keyfile"
        log "Foliate Flatpak reader theme selected: Livara.json"
        selected=true
      fi

      if [[ "$selected" != true ]]; then
        log "Foliate reader JSON theme generated; no native dconf or Flatpak keyfile backend available"
      fi
    }
    sync_foliate_theme_selection

    # Okular follows KDE's color-scheme preference, not qt6ct's palette alone.
    # The active shell owns the generated .colors file; this adapter selects it in the KDE
    # config without rewriting unrelated KDE application preferences.
    sync_kde_color_scheme() {
      local kdeglobals="$XDG_CONFIG_HOME/kdeglobals"
      local scheme_dir="${XDG_DATA_HOME:-$HOME/.local/share}/color-schemes"
      local scheme=""
      if [[ -s "$scheme_dir/DankMatugenDark.colors" ]]; then
        scheme="DankMatugenDark"
      elif [[ -s "$scheme_dir/DankMatugen.colors" ]]; then
        scheme="DankMatugen"
      fi
      [[ -n "$scheme" ]] || {
        log "KDE color scheme not selected: generated .colors file is not available yet"
        return 0
      }

      mkdir -p "$(dirname "$kdeglobals")"
      if [[ -f "$kdeglobals" ]]; then
        if grep -q '^\[General\]$' "$kdeglobals"; then
          if sed -n '/^\[General\]$/,/^\[/p' "$kdeglobals" | grep -q '^ColorScheme='; then
            sed -i "/^\[General\]$/,/^\[/ s/^ColorScheme=.*/ColorScheme=$scheme/" "$kdeglobals"
          else
            sed -i "/^\[General\]$/a ColorScheme=$scheme" "$kdeglobals"
          fi
        else
          printf '\n[General]\nColorScheme=%s\n' "$scheme" >> "$kdeglobals"
        fi
      else
        printf '[General]\nColorScheme=%s\n' "$scheme" > "$kdeglobals"
      fi
      log "KDE color scheme selected: $scheme"
    }
    sync_kde_color_scheme

    sync_freesm_theme_root() {
      local root="$1"
      [[ -n "$root" ]] || return 0
      local theme_root="$root/themes/livara"
      local manifest="$theme_root/theme.json"
      local qss="$theme_root/themeStyle.css"
      mkdir -p "$theme_root"

      write_atomic "$manifest" <<EOF
{
  "name": "Livara",
  "widgets": "Fusion",
  "qssFilePath": "themeStyle.css",
  "colors": {
    "Window": "$(json_color qt_window)",
    "WindowText": "$(json_color text)",
    "Base": "$(json_color qt_base)",
    "AlternateBase": "$(json_color mantle)",
    "ToolTipBase": "$(json_color mantle)",
    "ToolTipText": "$(json_color text)",
    "Text": "$(json_color text)",
    "Button": "$(json_color qt_button)",
    "ButtonText": "$(json_color text)",
    "BrightText": "$(json_color red)",
    "Link": "$(json_color blue)",
    "Highlight": "$(json_color qt_highlight)",
    "HighlightedText": "$(json_color on_primary)",
    "fadeColor": "$(json_color qt_window)",
    "fadeAmount": 0.5
  },
  "logColors": {
    "MessageHighlight": "$(json_color primary)",
    "LauncherHighlight": "$(json_color mauve)",
    "DebugHighlight": "$(json_color green)",
    "WarningHighlight": "$(json_color yellow)",
    "ErrorHighlight": "$(json_color red)",
    "FatalHighlight": "$(json_color red)",
    "Message": "$(json_color text)",
    "Launcher": "$(json_color mauve)",
    "Debug": "$(json_color green)",
    "Warning": "$(json_color yellow)",
    "Error": "$(json_color red)",
    "Fatal": "$(json_color crust)"
  }
}
EOF
      write_atomic "$qss" <<EOF
/* Livara Freesm Launcher theme; generated from the active wallpaper. */
QWidget { background-color: $(json_color qt_window); color: $(json_color text); }
QToolTip { background-color: $(json_color qt_window mantle); color: $(json_color text); border: 1px solid $(json_color qt_highlight blue); }
QPushButton, QComboBox, QSpinBox, QDoubleSpinBox { background-color: $(json_color qt_base); color: $(json_color text); border: 1px solid $(json_color overlay0); border-radius: 4px; padding: 4px 8px; }
QPushButton:hover, QComboBox:hover, QSpinBox:hover, QDoubleSpinBox:hover { background-color: $(json_color surface1); border-color: $(json_color blue); }
QPushButton:pressed, QPushButton:checked, QAbstractButton:checked { background-color: $(json_color qt_highlight); color: $(json_color on_primary); }
QLineEdit, QTextEdit, QPlainTextEdit, QListView, QTreeView, QTableView { background-color: $(json_color surface0); color: $(json_color text); border: 1px solid $(json_color overlay0); selection-background-color: $(json_color qt_highlight); selection-color: $(json_color on_primary); }
QListView::item:hover, QTreeView::item:hover, QTableView::item:hover { background-color: $(json_color surface1); }
QListView::item:selected, QTreeView::item:selected, QTableView::item:selected { background-color: $(json_color qt_highlight); color: $(json_color on_primary); }
QHeaderView::section { background-color: $(json_color mantle); color: $(json_color text); border: 1px solid $(json_color overlay0); padding: 4px; }
QGroupBox { border: 1px solid $(json_color overlay0); margin-top: 8px; padding-top: 8px; }
QSlider::groove:horizontal, QProgressBar { background-color: $(json_color surface0); border: 1px solid $(json_color overlay0); }
QSlider::handle:horizontal, QProgressBar::chunk { background-color: $(json_color blue); }
QScrollBar:vertical, QScrollBar:horizontal { background-color: $(json_color mantle); }
QScrollBar::handle:vertical, QScrollBar::handle:horizontal { background-color: $(json_color overlay0); border-radius: 4px; }
QCheckBox::indicator:checked, QRadioButton::indicator:checked { background-color: $(json_color blue); border: 1px solid $(json_color sapphire); }
EOF

      # Freesm reads ApplicationTheme from the canonical launcher config.
      # Never scan an arbitrary INI: that can mutate an unrelated application.
      local config="$root/freesmlauncher.cfg"
      if [[ ! -e "$config" ]]; then
        write_atomic "$config" <<CFG
[General]
ApplicationTheme=livara
CFG
      fi
      if [[ -n "$config" ]]; then
        if grep -q '^ApplicationTheme=' "$config"; then
          sed -i 's/^ApplicationTheme=.*/ApplicationTheme=livara/' "$config"
        elif grep -q '^\[General\]$' "$config"; then
          sed -i '/^\[General\]$/a ApplicationTheme=livara' "$config"
        fi
      fi
    }

    [[ -d "$FREESM_DATA_HOME" ]] && sync_freesm_theme_root "$FREESM_DATA_HOME"
    [[ -d "$FREESM_FLATPAK_HOME" ]] && sync_freesm_theme_root "$FREESM_FLATPAK_HOME"

    sync_xournal_theme() {
      local root="$1"
      local palette="$root/palettes/$XOURNAL_PALETTE_NAME"
      local palette_tmp
      mkdir -p "$(dirname "$palette")"
      palette_tmp="$(mktemp "$(dirname "$palette")/.livara-xournal.XXXXXX")"
      {
        local seen=""

        add_unique_color() {
          local rgb
          rgb="$(hex_to_rgb "$(json_color "$1" "${3:-base}")")"
          if [[ "|$seen|" == *"|$rgb|"* ]]; then
            return 0
          fi
          seen="${seen:+$seen|}$rgb"
          printf '%s %s\n' "$rgb" "$2"
        }

        printf '%s\n' 'GIMP Palette' 'Name: Livara' 'Columns: 4' '#'
        # GPL has no aliases: keep the first semantic role for equal RGB values.
        # Material roles are application-surface semantics, not drawing colors;
        # wallpaper-derived primary/container/secondary/tertiary roles often
        # collapse to the same RGB value. Keep stable drawing roles only and
        # let the RGB guard below enforce the contract for future palettes.
        add_unique_color text Text
        add_unique_color subtext0 Muted
        add_unique_color overlay1 Outline
        add_unique_color blue Blue
        add_unique_color sapphire Sapphire
        add_unique_color teal Teal
        add_unique_color green Green
        add_unique_color yellow Yellow
        add_unique_color peach Orange
        add_unique_color mauve Purple
        add_unique_color red Red
      } | write_atomic "$palette_tmp"

      if grep -Eiq '[[:space:]](Primary|Primary Container|Secondary|Tertiary|Error|Crust|Mantle)$' "$palette_tmp"; then
        rm -f "$palette_tmp"
        log "Xournal palette rejected: application role leaked into drawing colors"
        return 1
      fi
      if ! awk 'NF >= 3 && $1 ~ /^[0-9]+$/ { key = $1 FS $2 FS $3; if (++seen[key] > 1) duplicate = 1 } END { exit duplicate }' "$palette_tmp"; then
        rm -f "$palette_tmp"
        log "Xournal palette rejected: duplicate RGB entries"
        return 1
      fi
      mv -f "$palette_tmp" "$palette"

      local canvas_color grid_color selection_color canvas_argb selection_argb
      canvas_color="$(json_color xournal_canvas mantle)"
      grid_color="$(json_color xournal_grid overlay0)"
      selection_color="$(json_color xournal_selection blue)"
      canvas_argb="$(hex_to_argb_decimal "$canvas_color")"
      selection_argb="$(hex_to_argb_decimal "$selection_color")"
      local settings="$root/settings.xml"
      if [[ ! -e "$settings" ]]; then
        write_atomic "$settings" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<settings>
  <property name="colorPalette" value="$palette"/>
  <property name="backgroundColor" value="$canvas_argb"/>
  <property name="selectionBorderColor" value="$selection_argb"/>
  <property name="themeVariant" value="useSystem"/>
  <property name="pageTemplate" value="xoj/template&#10;backgroundType=graph&#10;backgroundTypeConfig=f1=$grid_color,af1=$canvas_color&#10;backgroundColor=$canvas_color&#10;"/>
  <property name="menubarVisible" value="false"/>
  <property name="defaultViewModeAttributes" value="showToolbar,showSidebar"/>
</settings>
EOF
        return 0
      fi
      [[ -f "$settings" && ! -L "$settings" ]] || return 0
      local settings_tmp="$settings.tmp.$$"
      awk -v palette="$palette" '
        BEGIN { updated = 0 }
        /<property[[:space:]]+name="colorPalette"/ { next }
        /<\/settings>/ && !updated {
          printf "  <property name=\"colorPalette\" value=\"%s\"/>\n", palette
          updated = 1
        }
        { print }
      ' "$settings" > "$settings_tmp"
      sed -i \
        -e 's|<property name="backgroundColor" value="[^"]*"/>|<property name="backgroundColor" value="'"$canvas_argb"'"/>|' \
        -e 's|<property name="selectionBorderColor" value="[^"]*"/>|<property name="selectionBorderColor" value="'"$selection_argb"'"/>|' \
        -e 's|backgroundTypeConfig=f1=#[0-9A-Fa-f]\{6\},af1=#[0-9A-Fa-f]\{6\}|backgroundTypeConfig=f1='"$grid_color"',af1='"$canvas_color"'|' \
        -e 's|<property name="menubarVisible" value="[^"]*"/>|<property name="menubarVisible" value="false"/>|' \
        -e 's|<property name="defaultViewModeAttributes" value="[^"]*"/>|<property name="defaultViewModeAttributes" value="showToolbar,showSidebar"/>|' \
        "$settings_tmp"
      mv -f "$settings_tmp" "$settings"
    }

    if [[ -s "$THEME_DIR/palette.json" ]]; then
      sync_xournal_theme "$XDG_CONFIG_HOME/xournalpp"
      [[ -d "$HOME/.var/app/com.github.xournalpp.xournalpp" ]] && sync_xournal_theme "$HOME/.var/app/com.github.xournalpp.xournalpp/config/xournalpp"
    fi

    sync_vesktop_theme_root() {
      local root="$1"
      [[ -n "$root" && -d "$root" ]] || return 0
      local themes_dir="$root/themes"
      local css="$themes_dir/livara-midnight.theme.css"
      mkdir -p "$themes_dir"
      write_atomic "$css" <<EOF
/**
 * @name Livara Midnight
 * @description Midnight Discord with the active $SHELL_NAME palette.
 * @source https://github.com/refact0r/midnight-discord
 */
@import url('https://refact0r.github.io/midnight-discord/build/midnight.css');

body {
  --font: '';
  --code-font: '';
  --gap: 12px;
  --border-thickness: 1px;
  --animations: on;
  --custom-window-controls: on;
  --top-bar-button-position: titlebar;
  --small-user-panel: off;
}

:root {
  --colors: on;
  --text-0: $(json_color base);
  --text-1: $(json_color text);
  --text-2: $(json_color subtext1);
  --text-3: $(json_color subtext0);
  --text-4: $(json_color overlay0);
  --text-5: $(json_color overlay1);
  --bg-1: $(json_color surface2);
  --bg-2: $(json_color surface1);
  --bg-3: $(json_color surface0);
  --bg-4: $(json_color base);
  --hover: color-mix(in srgb, $(json_color primary) 12%, transparent);
  --active: $(json_color surface2);
  --active-2: $(json_color surface1);
  --message-hover: color-mix(in srgb, $(json_color primary) 8%, transparent);
  --accent-1: $(json_color primary);
  --accent-2: $(json_color primary);
  --accent-3: $(json_color secondary);
  --accent-4: $(json_color secondary);
  --accent-5: $(json_color tertiary);
  --accent-new: $(json_color error);
  --online: $(json_color green);
  --dnd: $(json_color red);
  --idle: $(json_color yellow);
  --streaming: $(json_color mauve);
  --offline: $(json_color overlay0);
  --border-light: var(--hover);
  --border: var(--active);
  --border-hover: var(--active);
  --button-border: color-mix(in srgb, $(json_color text) 12%, transparent);
  --red-1: $(json_color red);
  --red-2: $(json_color red);
  --red-3: $(json_color red);
  --red-4: $(json_color red);
  --red-5: $(json_color red);
  --green-1: $(json_color green);
  --green-2: $(json_color green);
  --green-3: $(json_color green);
  --green-4: $(json_color green);
  --green-5: $(json_color green);
  --blue-1: $(json_color blue);
  --blue-2: $(json_color blue);
  --blue-3: $(json_color blue);
  --blue-4: $(json_color blue);
  --blue-5: $(json_color blue);
  --yellow-1: $(json_color yellow);
  --yellow-2: $(json_color yellow);
  --yellow-3: $(json_color yellow);
  --yellow-4: $(json_color yellow);
  --yellow-5: $(json_color yellow);
  --purple-1: $(json_color mauve);
  --purple-2: $(json_color mauve);
  --purple-3: $(json_color mauve);
  --purple-4: $(json_color mauve);
  --purple-5: $(json_color mauve);
}
EOF
      rm -f "$themes_dir/dank-discord.css" "$themes_dir/noctalia-material.theme.css" "$themes_dir/livara-material.theme.css"

      local settings="$root/settings/settings.json"
      local tmp="$settings.tmp.$$"
      mkdir -p "$(dirname "$settings")"
      if [[ -f "$settings" ]]; then
        jq '.enabledThemes = (((.enabledThemes // []) - ["dank-discord.css", "noctalia-material.theme.css", "livara-material.theme.css"] + ["livara-midnight.theme.css"]) | unique)' "$settings" > "$tmp"
      else
        jq -n '{enabledThemes: ["livara-midnight.theme.css"]}' > "$tmp"
      fi
      chmod 0644 "$tmp"
      mv -f "$tmp" "$settings"
      log "$SHELL_NAME Midnight Discord theme enabled: $css (restart Vesktop if it was already running)"
    }

    # Generate the CSS from the active shell palette and select it in Vencord;
    # mirror the same contract into an existing Vesktop Flatpak data root.
    sync_vesktop_theme_root "$VESKTOP_CONFIG_HOME"
    [[ -d "$HOME/.var/app/dev.vencord.Vesktop" ]] && sync_vesktop_theme_root "$VESKTOP_FLATPAK_HOME"

    foliate_root="$FOLIATE_CONFIG_HOME"
    [[ -d "$FOLIATE_FLATPAK_HOME" ]] && foliate_root="$FOLIATE_FLATPAK_HOME"
    freesm_root="$FREESM_DATA_HOME"
    [[ -d "$FREESM_FLATPAK_HOME" ]] && freesm_root="$FREESM_FLATPAK_HOME"
    xournal_root="$XDG_CONFIG_HOME/xournalpp"
    [[ -d "$HOME/.var/app/com.github.xournalpp.xournalpp/config/xournalpp" ]] && xournal_root="$HOME/.var/app/com.github.xournalpp.xournalpp/config/xournalpp"

    palette_applied=false
    [[ -s "$PALETTE_FILE" ]] && palette_applied=true

    nvim_applied=false
    [[ -s "$NVIM_THEME_PATH" ]] && nvim_applied=true

    foliate_applied=false
    # Verify via dconf (native) or keyfile (Flatpak). dconf read does not
    # need the GSettings schema to be installed on the host.
    if [[ -s "$foliate_root/themes/Livara.json" ]]; then
      if command -v dconf >/dev/null 2>&1 &&
         [[ "$(dconf read "$foliate_dconf_path" 2>/dev/null || true)" == "'Livara.json'" ]]; then
        foliate_applied=true
      fi
      if [[ "$foliate_applied" != true ]] &&
         [[ -f "$HOME/.var/app/com.github.johnfactotum.Foliate/config/glib-2.0/settings/keyfile" ]]; then
        foliate_keyfile="$HOME/.var/app/com.github.johnfactotum.Foliate/config/glib-2.0/settings/keyfile"
        if awk -v section="$foliate_keyfile_section" '
          BEGIN { in_section = 0 }
          /^\[/ { in_section = ($0 == "[" section "]") }
          in_section && /^theme='\''Livara.json\''$/ { found = 1; exit }
          END { exit !found }
        ' "$foliate_keyfile" 2>/dev/null; then
          foliate_applied=true
        fi
      fi
    fi

    kde_applied=false
    if [[ -s "${XDG_DATA_HOME:-$HOME/.local/share}/color-schemes/DankMatugenDark.colors" ||
          -s "${XDG_DATA_HOME:-$HOME/.local/share}/color-schemes/DankMatugen.colors" ]] &&
       grep -q '^ColorScheme=DankMatugen\(Dark\)\?$' "$XDG_CONFIG_HOME/kdeglobals" 2>/dev/null; then
      kde_applied=true
    fi

    freesm_applied=false
    if [[ -s "$freesm_root/themes/livara/theme.json" && -s "$freesm_root/themes/livara/themeStyle.css" ]]; then
      while IFS= read -r -d "" config; do
        if grep -q '^ApplicationTheme=livara$' "$config"; then
          freesm_applied=true
          break
        fi
      done < <(find "$freesm_root" -maxdepth 2 -type f \( -name '*.cfg' -o -name '*.ini' \) -print0 2>/dev/null)
    fi

    xournal_applied=false
    if [[ -s "$xournal_root/palettes/$XOURNAL_PALETTE_NAME" ]] &&
       grep -q 'name="colorPalette"' "$xournal_root/settings.xml" 2>/dev/null; then
      xournal_applied=true
    fi

    fastfetch_applied=false
    [[ -s "$FASTFETCH_CAT_OUTPUT" && -s "$THEME_DIR/fastfetch.jsonc" ]] && fastfetch_applied=true

    vesktop_applied=false
    for vesktop_root in "$VESKTOP_CONFIG_HOME" "$VESKTOP_FLATPAK_HOME"; do
      if [[ -s "$vesktop_root/themes/livara-midnight.theme.css" && -s "$vesktop_root/settings/settings.json" ]] &&
         jq -e --arg theme "livara-midnight.theme.css" '((.enabledThemes // []) | index($theme)) != null' "$vesktop_root/settings/settings.json" >/dev/null 2>&1; then
        vesktop_applied=true
        break
      fi
    done
    hydra_generated=false
    [[ -s "$HYDRA_THEME_EXPORT_DIR/theme.css" ]] && hydra_generated=true

    hydra_submission_ready=false
    [[ -n "$HYDRA_FRIEND_CODE" && -s "$HYDRA_SCREENSHOT_SOURCE" ]] && hydra_submission_ready=true
    hydra_applied=false

    # The overview distinguishes generated files from confirmed activation.
    # A file can exist while an app still needs a restart or a selected theme.
    write_atomic "$THEME_DIR/applied-applications.json" <<EOF
{
  "generatedFrom": "$SHELL_NAME application contracts",
  "applications": [
    {"name":"$SHELL_NAME palette","contract":"$SHELL_NAME palette variant $PALETTE_VARIANT for GTK/Qt/Kitty/WezTerm and application adapters","path":"$PALETTE_FILE","applied":$palette_applied,"activation":"active shell palette generated"},
    {"name":"GTK/libadwaita/GParted","contract":"GTK3/GTK4 gtk.css plus settings.ini generated from the active variant","path":"$XDG_CONFIG_HOME/gtk-3.0/gtk.css","applied":true,"activation":"restart GTK applications; no logout required"},
    {"name":"Zen/Firefox","contract":"profile-consumable userChrome.css imported by the declarative profile module","path":"$THEME_DIR/browser/firefox.css","applied":true,"activation":"restart Zen/Firefox after enabling userChrome.css"},
    {"name":"Neovim/NixVim","contract":"matugen_colors.lua + NixVim transparent highlight policy","path":"$NVIM_THEME_PATH","applied":$nvim_applied,"activation":"palette file generated and watched by NixVim"},
    {"name":"Foliate","contract":"Foliate reader JSON theme + viewer.view.theme (GTK4/libadwaita host UI)","path":"$foliate_root/themes/Livara.json","applied":$foliate_applied,"activation":"native or sandbox GSettings selection verified"},
    {"name":"KDE/Okular","contract":"Generated .colors + kdeglobals ColorScheme","path":"${XDG_CONFIG_HOME}/kdeglobals","applied":$kde_applied,"activation":"KDE color scheme selection verified"},
    {"name":"Freesm Launcher","contract":"themes/livara/theme.json + themeStyle.css + ApplicationTheme","path":"$freesm_root/themes/livara","applied":$freesm_applied,"activation":"ApplicationTheme selection verified"},
    {"name":"Xournal++","contract":"palettes/$XOURNAL_PALETTE_NAME + settings.xml colorPalette","path":"$xournal_root/palettes/$XOURNAL_PALETTE_NAME","applied":$xournal_applied,"activation":"restart Xournal++ after a palette change"},
    {"name":"Fastfetch","contract":"$SHELL_NAME primary color + generated keyColor hex + kitty-direct","path":"$THEME_DIR/fastfetch.jsonc","applied":$fastfetch_applied,"activation":"next invocation reads the generated config"},
    {"name":"btop","contract":"generated $BTOP_THEME + color_theme selection","path":"$BTOP_THEME","applied":true,"activation":"SIGUSR2 sent when btop is running"},
    {"name":"WezTerm","contract":"generated color scheme watched by the WezTerm Lua config","path":"$WEZTERM_THEME","applied":true,"activation":"automatically_reload_config handles reload"},
    {"name":"Vesktop","contract":"Midnight Discord CSS + Vencord enabledThemes","path":"$VESKTOP_CONFIG_HOME/themes/livara-midnight.theme.css","applied":$vesktop_applied,"activation":"restart Vesktop after external settings change"},
    {"name":"Hydra Launcher","contract":"theme.css export plus official hydra-themes publication layout","path":"$HYDRA_THEME_EXPORT_DIR/theme.css","exportPath":"$HYDRA_THEME_EXPORT_DIR/theme.css","applied":$hydra_applied,"generated":$hydra_generated,"registered":false,"activated":false,"submissionReady":$hydra_submission_ready,"activationRequired":true,"activation":"Hydra's Appearance list is LevelDB-owned; use Create/Edit and paste the generated CSS"}
  ]
}
EOF

    applied_count="$(jq '[.applications[] | select(.applied == true)] | length' "$THEME_DIR/applied-applications.json")"
    total_count="$(jq '.applications | length' "$THEME_DIR/applied-applications.json")"
    if [[ "$applied_count" == "$total_count" ]]; then
      log "theme adapters synchronized: $applied_count/$total_count active contracts (reload is application-specific)"
    else
      inactive_contracts="$(jq -r '[.applications[] | select(.applied != true) | .name] | join(", ")' "$THEME_DIR/applied-applications.json")"
      log "theme adapters generated with activation gaps: $applied_count/$total_count active contracts; inactive: $inactive_contracts"
    fi
