#!/usr/bin/env bash
set -Eeuo pipefail

XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
source_file="${AMBXST_COLORS_FILE:-$XDG_CACHE_HOME/ambxst/colors.json}"
theme_root="${LIVARA_THEME_ROOT:-$XDG_STATE_HOME/livara/theme}"
variant=dark

lock_file="${LIVARA_LOCK_FILE:-$XDG_STATE_HOME/livara/theme-sync.lock}"
if [[ "${LIVARA_LOCK_HELD:-0}" != 1 ]]; then
  mkdir -p "$(dirname "$lock_file")"
  exec 9>"$lock_file"
  if ! flock -n 9; then
    printf 'theme synchronization already running; skipping Ambxst palette bridge\n' >&2
    exit 0
  fi
fi

# Ambxst/Livara is dark-only. Do not allow stale environment values or manual
# callers to activate palette.light.json.
if [[ "${LIVARA_PALETTE_VARIANT:-dark}" != dark ]]; then
  printf 'Livara supports only the dark palette variant\n' >&2
  exit 2
fi
if [[ ! -s "$source_file" ]]; then
  if [[ "${LIVARA_REQUIRE_AMBXST:-0}" == 1 ]]; then
    printf 'Ambxst palette source is missing: %s\n' "$source_file" >&2
    exit 1
  fi
  exit 0
fi
command -v jq >/dev/null 2>&1 || exit 1

is_hex='^#[0-9A-Fa-f]{6}$'
color() {
  local key="$1"
  jq -er --arg key "$key" '.[$key] // error("missing color: " + $key)' "$source_file" \
    | grep -E "$is_hex"
}

# Validate every source role before publishing the canonical output.
for key in background surface surfaceContainer surfaceContainerHigh \
  overBackground outline outlineVariant primary secondary tertiary error blue cyan green magenta red yellow \
  overPrimary overSecondary overTertiary; do
  color "$key" >/dev/null
done

mkdir -p "$theme_root"
# This path was generated by an older bridge version; WezTerm is now written
# by the application-adapter phase in its documented config directory.
if [[ -f "$theme_root/wezterm/Ambxst.toml" || -L "$theme_root/wezterm/Ambxst.toml" ]]; then
  rm -f "$theme_root/wezterm/Ambxst.toml"
fi
rmdir "$theme_root/wezterm" 2>/dev/null || true
tmpdir="$(mktemp -d "$theme_root/.ambxst-palette.XXXXXX")"
cleanup() { rm -rf "$tmpdir"; }
trap cleanup EXIT

atomic_install() {
  local source="$1" target="$2" target_dir tmp
  target_dir="$(dirname "$target")"
  mkdir -p "$target_dir"
  tmp="$(mktemp "$target_dir/.livara-theme.XXXXXX")"
  cat "$source" > "$tmp"
  chmod 0644 "$tmp"
  mv -f -- "$tmp" "$target"
}

jq -n --slurpfile c "$source_file" '
  def c($key; $fallback): ($c[0][$key] // $c[0][$fallback]);
  {
    base: c("background"; "surface"),
    mantle: c("surfaceContainerLowest"; "surfaceContainer"),
    crust: c("surfaceContainerLowest"; "background"),
    surface0: c("surface"; "background"),
    surface1: c("surfaceContainer"; "surface"),
    surface2: c("surfaceContainerHigh"; "surfaceContainer"),
    surface3: c("surfaceContainerHigh"; "surfaceContainer"),
    text: c("overBackground"; "white"),
    on_surface: c("overBackground"; "white"),
    subtext0: c("outline"; "outlineVariant"),
    subtext1: c("outlineVariant"; "outline"),
    overlay0: c("outline"; "outlineVariant"),
    overlay1: c("outlineVariant"; "outline"),
    overlay2: c("overBackground"; "outlineVariant"),
    blue: c("primary"; "blue"),
    sapphire: c("blue"; "primary"),
    teal: c("secondary"; "cyan"),
    green: c("green"; "secondary"),
    yellow: c("yellow"; "tertiary"),
    peach: c("tertiary"; "primary"),
    maroon: c("error"; "red"),
    red: c("red"; "error"),
    mauve: c("tertiary"; "primary"),
    pink: c("magenta"; "primary"),
    lavender: c("primary"; "blue"),
    primary: c("primary"; "blue"),
    secondary: c("secondary"; "cyan"),
    tertiary: c("tertiary"; "primary"),
    error: c("error"; "red"),
    on_primary: c("overPrimary"; "background"),
    on_secondary: c("overSecondary"; "background"),
    on_tertiary: c("overTertiary"; "background"),
    on_error: c("overError"; "background"),
    gtk_window_bg: c("background"; "surface"),
    gtk_view_bg: c("surface"; "background"),
    gtk_accent: c("primary"; "blue"),
    gtk_border: c("outline"; "outlineVariant"),
    qt_window: c("background"; "surface"),
    qt_base: c("surface"; "background"),
    qt_highlight: c("primary"; "blue"),
    qt_highlight_text: c("overPrimary"; "background"),
    browser_chrome_bg: c("background"; "surface"),
    browser_surface: c("surface"; "background"),
    browser_surface_raised: c("surfaceContainerHigh"; "surfaceContainer"),
    browser_text: c("overBackground"; "white"),
    browser_muted: c("outline"; "outlineVariant"),
    browser_accent: c("primary"; "blue"),
    browser_on_accent: c("overPrimary"; "background"),
    browser_border: c("outline"; "outlineVariant"),
    niri_active_border: c("primary"; "blue"),
    niri_inactive_border: c("outline"; "outlineVariant"),
    xournal_canvas: c("surfaceContainerLowest"; "surfaceContainer"),
    xournal_grid: c("outline"; "outlineVariant"),
    xournal_selection: c("primary"; "blue")
  }
' > "$tmpdir/palette.$variant.json"
jq -e 'type == "object" and (to_entries | all(.value | type == "string" and test("^#[0-9A-Fa-f]{6}$")))' \
  "$tmpdir/palette.$variant.json" >/dev/null

# Keep palette.json as the currently active projection while preserving the
# other variant. The variant-specific file is the source selected by adapters.
cp "$tmpdir/palette.$variant.json" "$tmpdir/palette.json"

atomic_install "$tmpdir/palette.$variant.json" "$theme_root/palette.$variant.json"
atomic_install "$tmpdir/palette.json" "$theme_root/palette.json"
